### ISSUE TITLE
Setup for Adafruit's QT Py CH32V203 Dev Board

### ISSUE THREAD

**Issue by playfulkittykat** [Community-PIO-CH32V/platform-ch32v#103]
Product page: https://www.adafruit.com/product/5996

Hey! This is my first foray into platformio, though I do have some arduino experience. I'm having some trouble getting my CH32V203 board set up. Hopefully it's a simple problem on my end!

Here's my config:

```ini
[env]
platform = ch32v
framework = arduino
monitor_speed = 115200

[env:genericCH32V203G6U6]
board = genericCH32V203G6U6
upload_protocol = isp
build_flags =
  -DPIO_FRAMEWORK_ARDUINO_USBD
```

I can compile and upload, but no USB device shows up and it doesn't look like code executes correctly (tried the blink sketch).

Any help would be appreciated!

**Comment by symonty** [comment]
Do you see it listed in the terminal ? 

`pio device list`

if not you may need the driver for your platform, not sure. I am just a big platformIO user.

**Comment by playfulkittykat** [comment]
Nothing in `pio device list`, but I get this from `wchisp info`:

```
$ wchisp info
13:02:51 [INFO] Opening USB device #0
13:02:51 [INFO] Chip: CH32V203G6U6[0x3619] (Code Flash: 32KiB)
13:02:51 [INFO] Chip UID: CD-AB-80-5D-13-BC-60-C5
13:02:51 [INFO] BTVER(bootloader ver): 02.70
13:02:51 [INFO] Code Flash protected: false
13:02:51 [INFO] Current config registers: a55a3fc000ff19e6ffffffff00020700cdab805d13bc60c5
RDPR_USER: 0xC03F5AA5
  [7:0]   RDPR 0xA5 (0b10100101)
    `- Unprotected
  [16:16] IWDG_SW 0x1 (0b1)
    `- IWDG enabled by the software, and disabled by hardware
  [17:17] STOP_RST 0x1 (0b1)
    `- Disable
  [18:18] STANDBY_RST 0x1 (0b1)
    `- Disable, entering standby-mode without RST
  [23:22] SRAM_CODE_MODE 0x0 (0b0)
    `- CODE-192KB + RAM-128KB / CODE-128KB + RAM-64KB depending on the chip
DATA: 0xE619FF00
  [7:0]   DATA0 0x0 (0b0)
  [23:16] DATA1 0x19 (0b11001)
WRP: 0xFFFFFFFF
  `- Unprotected
```

**Comment by maxgerhardt** [comment]
> I can compile and upload, but no USB device shows up and it doesn't look like code executes correctly (tried the blink sketch).

We are currently not setting up the clock sources (HSE / HSI plus PLL) which prevents the USB code from starting up. This will be corrected shortly. (Related to #101).

**Comment by maxgerhardt** [comment]
The clock init issues have been fixed. Known development boards (not the "generic" boards) set their best clock source (HSE+PLL) out of the box. ([docs](https://pio-ch32v.readthedocs.io/en/latest/clock%20source%20configuration.html)).

We also now have a dedicated `board = adafruit_qtpy_ch32v203` definition. Also defaults to `isp` upload protocol.

To update your platform, use for example [PIO CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) -> `pio platform update -g -p ch32v`.

But due to link-time-optimization (LTO) not being disabled in the core yet (issue https://github.com/openwch/arduino_core_ch32/issues/204), the addition of the TinyUSB USB stack doesn't fit in the 32K flash memory of the chip. Even a simple "print via USB serial" takes 

```
Flash: [==========]  102.3% (used 33524 bytes from 32768 bytes)
```

Only simple non-USB sketches would work.

I will need to investigate and validate the proper build mechanism for this, as described in the issue. LTO can brick firmwares by optimizing the interrupt handlers away.

I hope to resolve this quickly this week.

**Comment by playfulkittykat** [comment]
Wow, thanks so much for taking a look so quickly! Unfortunately the blink example still isn't working. Are the pin definitions the same as would be in the Arduino IDE?

## `main.cpp`

```cpp
#include <Arduino.h>

// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(PB1, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(PB1, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(PB1, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}
```

## `platformio.ini`

```ini
[env]
platform = ch32v
framework = arduino
monitor_speed = 115200

[env:adafruit_qtpy_ch32v203]
board = adafruit_qtpy_ch32v203
```

**Comment by maxgerhardt** [comment]
Your code looks correct. PB1 is a validly defined pin (it's actually also "analog pin 0". There might be something wrong with the board either crashing before reaching `setup()` or `loop()`, or the Arduino core messing up the pin mapping functions when it comes to analog pins. I will investigate this with a debugger.

This worked in the Arduino IDE with which board selected under Tools -> Board? The latest "regular released" OpenWCH core does not yet have the "Adafruit QT Py CH32V203" as a selectable board, so you would have had to manually install the latest git version of the core somehow.

**Comment by maxgerhardt** [comment]
I tested your exact platformio.ini and code against a CH32V203 board that I have (it's C8 and not a G6 but otherwise should be equivalent, just flash sizes differences) and the PB1 pin **did** toggle. 

I've also fixed the clock setup for Arduino (previously only fixed for all other frameworks *except* Arduino, so you should definitely update your platform again.

If you have multiple folders in your VSCode workspace, make sure you use the [project environment switcher](https://docs.platformio.org/en/latest/integration/ide/vscode.html#project-tasks) to switch to the correct one.

**Comment by playfulkittykat** [comment]
I'm using arduino_core_ch32 at d76716239cdf8a084a5045c3dfd3151b3f69eeec in my Arduino IDE with these settings:

<img width="437" height="414" alt="Image" src="https://github.com/user-attachments/assets/3076b72e-8f30-4316-8d03-c0f050022793" />

Though I'm uploading by hand.

Notably this sketch does not include `Arduino.h`.

This blinks.

---

With `Community-PIO-CH32V/platform-ch32v` @ f0320ac04d5f70efe97ece1991bd1a9ee45af2b0 with the above code/ini, it does not blink.

**Comment by playfulkittykat** [comment]
> If you have multiple folders in your VSCode workspace, make sure you use the [project environment switcher](https://docs.platformio.org/en/latest/integration/ide/vscode.html#project-tasks) to switch to the correct one.

I'm using `pio run -t upload -e adafruit_qtpy_ch32v203`, no VSCode.

**Comment by maxgerhardt** [comment]
For me it works both in the Arduino IDE 1.8 and PlatformIO with the exact commit references you have and the exact code and `platformio.ini` you have. Is there any error shown while uploading the code? I measure the voltage change with a multimeter between GND and the PB1 pin.

The Arduino IDE is also wrong about the amount of flash that board has. They declare it as "224 KB" when it only has 32 KByte if the schematics are correct (**G6** not **G8** chip. Can you double check on your board?). And USB serial in that current version produces a version that is 35860 bytes.

**Comment by maxgerhardt** [comment]
So I was wrong about the flash size of a CH32V203 (https://github.com/openwch/arduino_core_ch32/issues/214) and you actually have 224K instead of just 32K on there, just the first 32K are "fast". Regardless, all the flash works and is usable. In the latest commit, I have
* corrected the board definition to use 224K for the Adafruit QT Py (31cba75064d6a55c43a838621b185f0688043d17)
* enabled and validated link time optimization to further reduce flash usage (https://github.com/Community-PIO-CH32V/arduino_core_ch32/commit/a4e27b660ae3dcf4ff8c82050ab9b1906bfd6d5b). This brings down a regular TinyUSB serial sketch to below 32K, especially with a few unnecessary USB modules ("USB video") disabled
 
The `tinyusb-arduino` example with the `adafruit_qtpy_ch32v203_tinyusb_usbd` environment should now be equivalent to your Arduino IDE setup. USB serial and pins should work as normal. Update via `pio platform update -g -p ch32v`.

**Comment by playfulkittykat** [comment]
Whatever you did fixed it! Both the LED and USB serial are now working. Thanks so much!
